version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Zipping artifacts..."
      - zip -r app.zip . 

artifacts:
  files:
    - app.zip
    - appspec.yml
